<img src="https://github.com/milena-seismo/DSB-Unit-03/blob/main/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# Regression Metrics

> All models are wrong, but some are useful.
>
> - <cite>George EP Box</cite>
---

### About
An introduction to Regression Metrics: what they are, how they work, and how use them to assess regression models in `scikit-learn`.

### Learning Objectives
- Describe the principles of regression metrics.
- Define common metrics including error measures (MAE, MSE, RMSE), R2, Adj R2 and others.
- Apply regression metrics to assess OLS models.


### Notebook Guide

- Metric #1 (Warmup): Euclidean Distance
- Prologue: Let's fit a model!
- Metric #2: Sum Squared Error (SSE)
- Metric #3: Mean Squared Error (MSE)
- Metric #4: The Coefficient of Determination (R2)
- Metric #5: Mean Absolute Deviation
- Conclusion and Takeaways

# Imports
As always... come back to this cell when you want to add more imports!

# Metric #1 (Warmup): Euclidean Distance

In [1]:
y = [4, 18, 9, 2, 7, 5]
y_hat = [3, 15, 8, 1, 8, 12]

In [ ]:
# Compute the distance via a listcomp!

In [ ]:
# Compute the distance via numpy!

# Prologue: Let's fit a model!

In [3]:
# Read in ad data
import pandas as pd

ads = pd.read_csv('https://raw.githubusercontent.com/milena-seismo/DSB-Unit-03/refs/heads/main/data/Advertising.csv')

In [5]:
ads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   TV          200 non-null    float64
 2   radio       200 non-null    float64
 3   newspaper   200 non-null    float64
 4   sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [6]:
ads_cp = ads.drop(columns='Unnamed: 0')

In [7]:
ads_cp.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [8]:
ads_cp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [10]:
ads_cp.describe()

               TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [10]:
# (THREAD) Drop unnamed col

### Think
Look at this data. What do you think is a good question to ask that we might model?

### Quick EDA
Let's poke around this data to see what we're working with.

In [ ]:
# Create the design matrix (X) and response vector (y)

In [ ]:
# Fit a linear regression model

In [ ]:
# Create a prediction vector y_hat

In [ ]:
# Interpret one of the slopes for me!

# Metric #2: Sum Squared Error (SSE)

In [ ]:
# Compute the SSE using numpy

# Metric #3: Mean Squared Error (MSE)

In [ ]:
# Compute the MSE using numpy

In [ ]:
# Compute the MSE using sklearn!

### Metric #3.5: The Root Mean Squared Error (RMSE)

In [ ]:
# Compute the RMSE! Does it make sense?

# Metric #4: The Coefficient of Determination ($R^2$)

In [ ]:
# Let's compute it "by hand"

In [ ]:
# Can also compute directly via sklearn!

In [ ]:
# ...and via metrics

In [ ]:
# Let's compute the SSE, MSE, RMSE of the null model.

In [ ]:
# Compare to our OLS model:

# Metric #5: Mean Absolute Deviation

In [ ]:
# Compute!

# Conclusion and Takeaways
In this lesson, we:

- Learned what distance metrics are (mathematically) and how they might apply to us
- Learned several regression error metrics, and why/when we might use them
- Explored the `sklearn.metrics` submodule and poked around all the different metrics it provides